// This file is automatically generated from your CSS. Any edits will be overwritten.
export const circularProgress: string;
export const rotate: string;
export const circle: string;
export const dash: string;
