// This file is automatically generated from your CSS. Any edits will be overwritten.
export const button: string;
export const buttonDisabled: string;
export const buttonInvert: string;
export const buttonInvertDisabled: string;
export const buttonRounded: string;
export const buttonOutline: string;
