// This file is automatically generated from your CSS. Any edits will be overwritten.
export const cardsList: string;
export const cardItem: string;
export const card: string;
export const cardImage: string;
export const cardTitle: string;
export const cardDescription: string;
