// This file is automatically generated from your CSS. Any edits will be overwritten.
export const ttuWrapper: string;
export const ttuContainer: string;
export const ttuTitle: string;
export const ttuImage: string;
export const ttuForm: string;
export const ttuFormButton: string;
export const ttuDialogContainer: string;
export const ttuDialogTitle: string;
export const ttuDialogBody: string;
export const ttuDialogImage: string;
export const ttuDialogButton: string;
