// This file is automatically generated from your CSS. Any edits will be overwritten.
export const header: string;
export const headerContainer: string;
export const isHidden: string;
export const isOver: string;
export const nav: string;
