// This file is automatically generated from your CSS. Any edits will be overwritten.
export const dialogRoot: string;
export const dialogBackdropRoot: string;
export const dialogContentContainer: string;
