// This file is automatically generated from your CSS. Any edits will be overwritten.
export const textFieldIsActive: string;
export const textFieldLabel: string;
export const textFieldIsFilled: string;
export const textField: string;
export const textFieldDisabled: string;
export const textFieldInput: string;
export const textFieldTextarea: string;
